"""
This file stores all prompt templates for the multi-agent system.
"""
from langchain_core.prompts import ChatPromptTemplate


def get_planning_prompt() -> ChatPromptTemplate:
    """
    Returns the `ChatPromptTemplate` used by the planning orchestrator.

    This template expects the following variables when you call `.format()` or
    `.partial()` on it:

    - **objective** (`str`): High-level goal the planner should achieve. This is
      what the planner decomposes into a sequence of steps.
    - **available_players** (`str`): Human-readable description of all players
      that can be assigned to steps (e.g. a bullet list with names and roles).
    - **format_instructions** (`str`): Instructions describing the exact JSON
      schema the planner must output (typically generated by an `OutputParser`).
    """
    return ChatPromptTemplate.from_messages(
        [
            (
                "system",
                """You are an expert planner agent for a multi-step meta-analysis workflow.
Given an overall objective, brief context information, and a list of available players,
your job is to produce a clear, dataflow-consistent step-by-step plan.

Planning rules:
- Create a concise, efficient plan with consolidated steps. Avoid unnecessary granularity - combine related operations into single steps where possible.
- Use a logical multi-step flow built around explicit artifacts:
  1. **Value identification step** – extract a list of `(field, value)` tuples from the document, following the meta-analytic schema, and store them in an artifact like `field_value_pairs`.
  2. **Tagging step (labeller)** – take the raw document and `field_value_pairs`, and produce a deterministically tagged document `labeled_text` (XML tags around the values).
  3. **Record structuring step** – take `labeled_text` (and schema) and produce structured records (e.g., `proposed_meta_analysis_records`).
  4. **Validation/finalization step** – take the proposed records and produce `final_meta_analysis_records`.
- Consolidate related tasks when it improves clarity and robustness, but keep the distinction between **value identification**, **tagging**, **structuring**, and **validation** clear in the artifacts you define.
- For each step, specify: `task`, `player`, `inputs`, `outputs`, `rationale`,
  and (if relevant) `target_resources`.
- Make each `task` explicitly mention the meta-analytic variables or schema fields it focuses on,
  so downstream players know which values to extract, tag, or refine.
- Prioritize efficiency: fewer, well-designed steps are better than many small steps.

Meta-analytic schema handling (CRITICAL):
- The meta-analytic schema will usually be provided as JSON or as `field: description` pairs
  (e.g., `"location": "study location (prefer coordinates...)"`).
- Treat the **field names** (JSON keys / text before the colon) as the exact keys that MUST
  appear in all meta-analysis record artifacts (`proposed_meta_analysis_records`,
  `refined_meta_analysis_records`, `final_meta_analysis_records`).
- The natural-language descriptions in the schema are ONLY guidance; they must never appear
  as record values. Each record value must be the concrete value extracted from the documents
  (e.g., `"location": "Tongshan experimental station, Xuzhou City, ..."`), not the description
  text itself.
- Do NOT introduce new top-level keys or rename schema fields in the final records. The final
  `final_meta_analysis_records` artifact must be a JSON structure whose record objects use
  exactly and only the schema-defined field names.

Player assignment (CRITICAL - use exact player names from available players list):
- Tasks that involve **identifying and listing concrete schema-relevant values** (as `(field, value)` pairs) → assign to **"value_identifier"**
- Tasks that involve **tagging** the original document with XML tags based on those values → assign to **"labeller"**
- Tasks that involve **reasoning, linking, aggregating, or structuring** labeled values into records → assign to **"schema_reasoner"**
- Tasks that involve **reviewing, critiquing, or quality checking** → assign to **"critic"**
- Tasks that involve **validating, correcting, or finalizing** records against schema → assign to **"schema_expert"**
- You MUST use the exact player names as they appear in the available players list; do not invent new names.

Objective visibility control (IMPORTANT):
- The full objective will be stored as an artifact. You can control which parts each step sees using `objective_sections`.
- For the **labeller** step (Step 1), it will AUTOMATICALLY only see labeling-related sections - you don't need to specify this.
- For other steps, you can optionally specify `objective_sections` as a list of section names (e.g., ["extraction", "validation"]) if you want to limit what they see.
- If `objective_sections` is not specified or empty, the step sees the full objective.
- This helps prevent confusion - e.g., the labeller won't see extraction/structuring instructions that might cause it to create structured output instead of tagging the original document.

Dataflow correctness (CRITICAL):
- Step 1 MUST have `inputs` as an empty dict (i.e., `inputs: {{}}`). Do NOT reference any artifacts in step 1.
- Every artifact referenced in any `inputs` MUST be produced by a previous step’s `outputs`.
  If an artifact is needed later (e.g., the meta-analytic schema text or a list of records),
  add an earlier step that produces it first.
- Ensure the dataflow is coherent: later steps should only depend on artifacts that exist,
  and every step’s `outputs` should be actually used by some later step or be a final output.
- NEVER treat the ExecutionContext name (e.g., "paper_to_extract") or any raw document text as a plan artifact.
  Context names and resources are accessed directly by players and must NOT appear in `inputs` or `outputs`.
- In particular, do NOT create inputs like {{"document": "paper_to_extract"}} or {{"document_text": "paper_to_extract"}}
  or use any context/resource name as an artifact name. The labeller and value_identifier read the original
  document directly from the context and do NOT need a `document` or `document_text` artifact.
- The only valid artifact names in `inputs` are those that have appeared previously in some step’s `outputs`
  (e.g., "field_value_pairs", "labeled_text", "proposed_meta_analysis_records",
  "refined_meta_analysis_records", "final_meta_analysis_records").
- For the tagging step with player "labeller", the typical inputs should be ONLY:
  {{"field_value_pairs": "field_value_pairs"}}, and the outputs should be ["labeled_text"].

Output expectations:
- The final artifacts should be JSON-compatible structures representing meta-analytic records
  (e.g., a list of objects or one JSON object per record), where keys are schema field names
  and values are the extracted values (including units where relevant).

Recommended artifact names (use consistently):
- field_value_pairs (produced by value_identifier in Step 1)
- labeled_text (produced by labeller in Step 2)
- proposed_meta_analysis_records
- refined_meta_analysis_records
- final_meta_analysis_records

Note: Do NOT create a "meta_analytic_schema" artifact - the schema is already provided in the objective.

Context:
{context_info}

Available players:
{available_players}

Output:
Return ONLY a JSON object that strictly follows this schema:
{format_instructions}
""",
            ),
            (
                "human",
                "Generate a complete plan to achieve the following objective: '{objective}'.",
            ),
        ]
    )


def get_task_execution_prompt() -> ChatPromptTemplate:
    """
    Returns the prompt template for task execution by a player.
    """
    return ChatPromptTemplate.from_messages(
        [
            (
                "system",
                """You are {player_name}. {role_prompt}

You are executing a specific task as part of a larger workflow.
Your goal is to complete the task thoroughly and provide actionable results.

**Available Tools:**
{tool_descriptions}
""",
            ),
            (
                "human",
                """**Task:** {task}

**Context Information:**
{context_info}

**Target Resources for This Step:** {target_resources}

**Context from Previous Steps:**
{input_context}

**Tool Results:**
{tool_results}

Execute this task and provide a comprehensive response.
""",
            ),
        ]
    )


def get_initial_work_prompt() -> ChatPromptTemplate:
    """
    Returns the prompt for generating initial work in a debate.
    """
    return ChatPromptTemplate.from_messages(
        [
            (
                "system",
                """You are {player_name}. {role_prompt}

You are participating in a multi-agent debate. Your goal is to provide
your unique perspective and insights based on your expertise.
""",
            ),
            (
                "human",
                """**Task:** {task}

**Context Information:**
{context_info}

**Target Resources:** {target_resources}

**Available Context:**
{context}

Provide your initial analysis.
""",
            ),
        ]
    )


def get_critique_prompt() -> ChatPromptTemplate:
    """
    Returns the prompt for critiquing other players' work.
    """
    return ChatPromptTemplate.from_messages(
        [
            ("system", "You are {player_name}. {role_prompt}"),
            (
                "human",
                """**Task being analyzed:** {task}

**Work from other players to critique:**

{other_work}

Provide your detailed critique.
""",
            ),
        ]
    )


def get_revision_prompt() -> ChatPromptTemplate:
    """
    Returns the prompt for revising work based on critiques.
    """
    return ChatPromptTemplate.from_messages(
        [
            ("system", "You are {player_name}. {role_prompt}"),
            (
                "human",
                """**Task:** {task}

**Your Original Analysis:**
{original_work}

**Critiques Received:**
{critiques}

Provide your revised analysis.
""",
            ),
        ]
    )


def get_synthesis_prompt() -> ChatPromptTemplate:
    """
    Returns the prompt for synthesizing multiple analyses into one.
    """
    return ChatPromptTemplate.from_messages(
        [
            (
                "system",
                """You are a synthesis expert responsible for combining multiple analyses into a single, structured output.
- Be CONCISE: Output only the essential information.
- Be STRUCTURED: Use a clean key-value format or JSON structure.
- NO lengthy explanations or narratives.
- Focus on FACTS, not process descriptions.

**CRITICAL SCHEMA COMPLIANCE**:
- If a meta-analytic schema is provided in the analyses or workspace, you MUST use EXACTLY the field names from that schema.
- Do NOT invent new field names or rename schema fields.
- Extract values from the analyses and map them to the exact schema field names (e.g., 'crop_type', 'yield_value', 'location', 'year', 'Treatment', 'Tillage', 'Soil_property', 'climate', 'remote_sensing_data').
- The schema field names are the ONLY valid keys for meta-analytic records.

If the task requires JSON output:
- Output RAW JSON only - do NOT wrap in markdown code blocks (no ```json or ```).
- Do NOT include any explanatory text before or after the JSON.
- Output ONLY valid JSON that can be directly parsed.
- Ensure all record objects use exactly the schema-defined field names.
""",
            ),
            (
                "human",
                """**Task that was analyzed:** {task}

**Analyses from all participants:**

{all_results}

Produce the final, structured output. If a meta-analytic schema was provided, ensure all records strictly conform to its field names.
""",
            ),
        ]
    )

